package org.example.pccwtest.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldDefaults;

/**
 * Entity class representing a user in the system.
 * <p>
 * This class maps to the "users" table in the database and contains information about each user, including
 * their username, email, password, and account status.
 * </p>
 */
@Getter
@Setter
@Entity
@FieldDefaults(level = AccessLevel.PRIVATE)
@Table(name = "users")
@AllArgsConstructor
@NoArgsConstructor
public class User {

    /**
     * The unique identifier of the user.
     * <p>
     * This field is auto-generated by the database.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;

    /**
     * The username of the user.
     * <p>
     * This field is used for user authentication and should be unique.
     * </p>
     */
    String username;

    /**
     * The email address of the user.
     * <p>
     * This field is used for communication purposes and should be unique.
     * </p>
     */
    String email;

    /**
     * The password of the user.
     * <p>
     * This field is used for user authentication.
     * </p>
     */
    @JsonIgnore
    String password;

    /**
     * Indicates whether the user's account is active.
     * <p>
     * This field is used to enable or disable user accounts.
     * </p>
     */
    Boolean isActive;
}